---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    run: xorg 
  name: xorg 
  namespace: desktop
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: xorg 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: xorg 
    spec:
      containers:
      - env:
        - name: DISPLAY
          value: :1
        image: quay.io/jcallen/kubernetes-desktop:latest
        imagePullPolicy: Always
        name: xorg 
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/.X11-unix
          name: x11-socket
        - mountPath: /dev/dri
          name: dri
        - mountPath: /dev/tty0
          name: tty
        - mountPath: /dev/input
          name: input
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: kn1.virtomation.com
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /dev/tty0
          type: ""
        name: tty
      - hostPath:
          path: /dev/dri
          type: ""
        name: dri
      - hostPath:
          path: /dev/input
          type: ""
        name: input
      - hostPath:
          path: /tmp/.X11-unix
          type: ""
        name: x11-socket
